dataset_config:
  # Whether to use commas to separate numbers right-to-left
  use_commas: false 
  # The proportion of each split to use for testing
  test_size: 0.2 
  # The proportion of problems in [DIFFICULTY]_float that are float [operator] float
  # 1 - float_float_problem_proportion is the proportion of problems that are float [operator] integer
  float_float_problem_proportion: 0.3 
splits:
  very_easy_int:
    # The number of arithmetic problems to generate (train + test, all operators)
    num_problems: 5000 
    # The lower bound of the exponent range (base 10)
    min_exponent: 0 
    # The upper bound of the exponent range (base 10)
    max_exponent: 1 
  very_easy_float:
    num_problems: 5000
    min_exponent: 0
    max_exponent: 1
    # The maximum precision to use when rounding the number
    max_rounding_precision: 1 
  easy_int: 
    num_problems: 5000
    min_exponent: 1
    max_exponent: 2
  easy_float:
    num_problems: 5000
    min_exponent: 1
    max_exponent: 2
    max_rounding_precision: 2 
  med_int: 
    num_problems: 5000
    min_exponent: 2
    max_exponent: 3
  med_float:
    num_problems: 5000
    min_exponent: 2
    max_exponent: 3
    max_rounding_precision: 3 
  hard_int: 
    num_problems: 5000
    min_exponent: 3
    max_exponent: 5
  hard_float:
    num_problems: 5000
    min_exponent: 3
    max_exponent: 5
    max_rounding_precision: 4 

